load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_generator",
    hdrs = [
        "id_generator.h",
        "id_generator.hpp",
    ],
)
