py_test(
    name = "test",
    srcs = ["test.py"],
    data = [
        "//modules/greet:pygreet.so"
    ],
    imports = [
        "//modules/greet:pygreet.so"
    ],
    python_version = "PY3",
    srcs_version = "PY3",
)