load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "world",
    srcs = ["world.cxx"],
    hdrs = ["world.h"],
    visibility = ["//visibility:public"]
)

# ==>
# bazel-bin/modules/world/libworld.a
# bazel-bin/modules/world/libworld.so