load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "world",
    srcs = ["world.cpp"],
    hdrs = ["world.hpp"],
)

# ==>
# bazel-bin/modules/world/libworld.a
# bazel-bin/modules/world/libworld.so